import { ParentProfile, MedicalReport, FollowUpItem } from '../types/medical';

export const INITIAL_PARENT_PROFILES: ParentProfile[] = [
  {
    id: 'parent_mother',
    name: 'Lakshmi Devi',
    relationship: 'Mother',
    age: 58,
    gender: 'Female',
    bloodGroup: 'O+',
    primaryCondition: 'Type 2 Diabetes & Hypertension',
    conditions: ['Type 2 Diabetes', 'Hypertension', 'Diabetic Nephropathy Risk'],
    primaryDoctor: 'Dr. Aris Thorne (Endocrinologist)',
    hospital: 'Apex Heart & Metabolic Institute',
    emergencyContactName: 'Rohan Devi (Son / Caregiver)',
    emergencyContactPhone: '+1 (555) 392-8812',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
  },
  {
    id: 'parent_father',
    name: 'Ramesh Devi',
    relationship: 'Father',
    age: 62,
    gender: 'Male',
    bloodGroup: 'B+',
    primaryCondition: 'Hypertension & Hyperlipidemia',
    conditions: ['Essential Hypertension', 'Hypercholesterolemia', 'Mild CAD Risk'],
    primaryDoctor: 'Dr. Evelyn Vance (Cardiologist)',
    hospital: 'St. Jude Cardiac Center',
    emergencyContactName: 'Rohan Devi (Son / Caregiver)',
    emergencyContactPhone: '+1 (555) 392-8812',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
  },
];

// Helper to generate sample SVG prescription base64
function makeSampleSvgBase64(docName: string, patientName: string, dateStr: string, textContent: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="750" viewBox="0 0 600 750" fill="#ffffff">
    <rect width="600" height="750" fill="#ffffff" stroke="#cbd5e1" stroke-width="2"/>
    <rect x="30" y="30" width="540" height="80" fill="#f8fafc" rx="8"/>
    <text x="50" y="70" font-family="Arial" font-size="20" font-weight="bold" fill="#0f172a">CARE CLINICAL PRESCRIPTION SCAN</text>
    <text x="50" y="95" font-family="Arial" font-size="12" fill="#475569">${docName} | Date: ${dateStr}</text>
    <line x1="30" y1="130" x2="570" y2="130" stroke="#cbd5e1" stroke-width="2"/>
    <text x="50" y="165" font-family="Arial" font-size="13" font-weight="bold" fill="#2563eb">PATIENT: ${patientName}</text>
    <foreignObject x="50" y="190" width="500" height="500">
      <div xmlns="http://www.w3.org/1999/xhtml" style="font-family: Arial; font-size: 13px; color: #334155; line-height: 1.6;">
        ${textContent}
      </div>
    </foreignObject>
  </svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

// 5 Distinct Reports for Mother (Lakshmi Devi)
export const MOTHER_REPORTS: MedicalReport[] = [
  {
    id: 'report_m1',
    parentId: 'parent_mother',
    uploadDate: '2026-07-18T10:30:00Z',
    visitDate: '2026-07-18',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Outpatient Endocrinology',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    fileUrl: makeSampleSvgBase64('Dr. Aris Thorne', 'Lakshmi Devi', 'July 18, 2026', 'Metformin dosage increased to 1000mg twice daily. Ramipril 5mg continued. HbA1c: 7.8%. Creatinine: 1.1 mg/dL.'),
    diagnoses: ['Type 2 Diabetes (Uncontrolled)', 'Essential Hypertension'],
    medicines: [
      { name: 'Metformin HCl', dosage: '1000 mg', frequency: 'Twice daily', status: 'changed', previousDosage: '500 mg', confidence: 96 },
      { name: 'Ramipril', dosage: '5 mg', frequency: 'Once daily', status: 'changed', previousDosage: '2.5 mg', confidence: 94 },
      { name: 'Vitamin D3', dosage: '60,000 IU', frequency: 'Once weekly', status: 'new', confidence: 92 },
    ],
    labResults: [
      { testName: 'HbA1c', value: 7.8, unit: '%', referenceRange: '4.0 - 5.6', status: 'abnormal_high', confidence: 98 },
      { testName: 'Fasting Blood Glucose', value: 154, unit: 'mg/dL', referenceRange: '70 - 99', status: 'abnormal_high', confidence: 96 },
      { testName: 'Serum Creatinine', value: 1.1, unit: 'mg/dL', referenceRange: '0.6 - 1.0', status: 'abnormal_high', confidence: 95 },
      { testName: 'Systolic BP', value: 142, unit: 'mmHg', referenceRange: '90 - 120', status: 'abnormal_high', confidence: 97 },
      { testName: 'Diastolic BP', value: 88, unit: 'mmHg', referenceRange: '60 - 80', status: 'abnormal_high', confidence: 97 },
    ],
    doctorRecommendations: ['Low-sodium diet', 'Daily 30-min walk', 'Repeat HbA1c in 90 days'],
    followUpDate: '2026-10-18',
    aiConfidenceScore: 95,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: "Mother's HbA1c increased to 7.8%. Dr. Thorne increased Metformin dosage from 500mg to 1000mg twice daily. Ramipril adjusted to 5mg. Vitamin D3 started.",
    changeHighlights: [
      { id: 'mc1', field: 'Metformin', category: 'medicine', oldValue: '500 mg', newValue: '1000 mg twice daily', description: 'Dosage increased due to elevated glycemic levels.', severity: 'warning' },
      { id: 'mc2', field: 'HbA1c', category: 'lab', oldValue: '7.4%', newValue: '7.8%', description: 'Glycemic control worsened over 2.5 months.', severity: 'warning' },
    ],
  },
  {
    id: 'report_m2',
    parentId: 'parent_mother',
    uploadDate: '2026-06-12T14:15:00Z',
    visitDate: '2026-06-12',
    doctorName: 'Dr. Vikram Seth',
    doctorSpecialty: 'Orthopedics',
    hospital: 'City Spine & Joint Care',
    department: 'Orthopedics OPD',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    fileUrl: makeSampleSvgBase64('Dr. Vikram Seth', 'Lakshmi Devi', 'June 12, 2026', 'Bilateral Knee Osteoarthritis. Prescribed Naproxen Sodium 500mg twice daily for joint pain.'),
    diagnoses: ['Bilateral Knee Osteoarthritis', 'Joint Pain'],
    medicines: [
      { name: 'Naproxen Sodium', dosage: '500 mg', frequency: 'Twice daily', status: 'new', confidence: 74 },
    ],
    labResults: [],
    doctorRecommendations: ['Physiotherapy exercises', 'Avoid stair climbing'],
    followUpDate: '2026-08-15',
    aiConfidenceScore: 74,
    needsReview: true,
    aiMode: 'simulator',
    caregiverSummary: 'Orthopedic visit for knee pain. Naproxen (NSAID) prescribed. [AI Flag]: NSAIDs present a renal risk with her elevated Creatinine (1.1). Manual review required.',
    changeHighlights: [
      { id: 'mc3', field: 'Naproxen 500mg', category: 'medicine', newValue: '500 mg twice daily', description: 'NSAID painkiller prescribed.', severity: 'critical' },
    ],
    doctorConflicts: [
      {
        id: 'conflict_m1',
        severity: 'critical',
        title: 'NSAID Painkiller & Kidney Function Risk',
        description: 'Dr. Vikram Seth (Orthopedics) prescribed Naproxen 500mg (NSAID). However, Dr. Aris Thorne (Endocrinologist) noted elevated Creatinine (1.1 mg/dL). NSAIDs can impair renal blood flow.',
        doctorNames: ['Dr. Vikram Seth (Orthopedics)', 'Dr. Aris Thorne (Endocrinology)'],
        reportIds: ['report_m2', 'report_m1'],
        recommendation: 'Consult Dr. Thorne before starting Naproxen or request a kidney-safe alternative (Acetaminophen).',
      },
    ],
  },
  {
    id: 'report_m3',
    parentId: 'parent_mother',
    uploadDate: '2026-05-05T09:00:00Z',
    visitDate: '2026-05-05',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Metabolic Lab',
    patientName: 'Lakshmi Devi',
    reportType: 'lab',
    fileUrl: makeSampleSvgBase64('Dr. Aris Thorne', 'Lakshmi Devi', 'May 05, 2026', 'Routine Diabetes Panel: HbA1c 7.4%, Fasting Glucose 140 mg/dL, Serum Creatinine 1.0 mg/dL.'),
    diagnoses: ['Type 2 Diabetes', 'Hypertension'],
    medicines: [
      { name: 'Metformin HCl', dosage: '500 mg', frequency: 'Twice daily', status: 'continued', confidence: 97 },
    ],
    labResults: [
      { testName: 'HbA1c', value: 7.4, unit: '%', referenceRange: '4.0 - 5.6', status: 'abnormal_high', confidence: 99 },
      { testName: 'Fasting Blood Glucose', value: 140, unit: 'mg/dL', referenceRange: '70 - 99', status: 'abnormal_high', confidence: 98 },
      { testName: 'Serum Creatinine', value: 1.0, unit: 'mg/dL', referenceRange: '0.6 - 1.0', status: 'normal', confidence: 97 },
      { testName: 'Systolic BP', value: 136, unit: 'mmHg', referenceRange: '90 - 120', status: 'abnormal_high', confidence: 96 },
    ],
    doctorRecommendations: ['Maintain diet restrictions'],
    followUpDate: '2026-07-15',
    aiConfidenceScore: 97,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Routine 3-month diabetes follow-up. HbA1c recorded at 7.4% (up from 6.9%). Metformin 500mg maintained.',
    changeHighlights: [
      { id: 'mc4', field: 'HbA1c', category: 'lab', oldValue: '6.9%', newValue: '7.4%', description: 'HbA1c increased by 0.5%.', severity: 'warning' },
    ],
  },
  {
    id: 'report_m4',
    parentId: 'parent_mother',
    uploadDate: '2026-01-20T11:20:00Z',
    visitDate: '2026-01-20',
    doctorName: 'Dr. Maya Lin',
    doctorSpecialty: 'Ophthalmology',
    hospital: 'Vision First Eye Hospital',
    department: 'Retinal Clinic',
    patientName: 'Lakshmi Devi',
    reportType: 'general',
    fileUrl: makeSampleSvgBase64('Dr. Maya Lin', 'Lakshmi Devi', 'Jan 20, 2026', 'Diabetic Retinopathy Screening: No macular edema or retinopathy detected. Eye drops prescribed.'),
    diagnoses: ['Diabetic Retinopathy Screening', 'Presbyopia'],
    medicines: [
      { name: 'Lubricating Eye Drops', dosage: '1 drop', frequency: '4x daily', status: 'new', confidence: 98 },
    ],
    labResults: [],
    doctorRecommendations: ['Fundus scan clear', 'Annual eye scan in Jan 2027'],
    followUpDate: '2027-01-20',
    aiConfidenceScore: 98,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Annual eye scan by Dr. Maya Lin. NO diabetic retinopathy detected. Reading glasses updated.',
    changeHighlights: [],
  },
  {
    id: 'report_m5',
    parentId: 'parent_mother',
    uploadDate: '2026-01-10T16:00:00Z',
    visitDate: '2026-01-10',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Endocrinology Clinic',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    fileUrl: makeSampleSvgBase64('Dr. Aris Thorne', 'Lakshmi Devi', 'Jan 10, 2026', 'HbA1c 6.9%. Glycemic control stable. Regimen unchanged.'),
    diagnoses: ['Type 2 Diabetes', 'Hypertension'],
    medicines: [
      { name: 'Metformin HCl', dosage: '500 mg', frequency: 'Twice daily', status: 'continued', confidence: 99 },
    ],
    labResults: [
      { testName: 'HbA1c', value: 6.9, unit: '%', referenceRange: '4.0 - 5.6', status: 'abnormal_high', confidence: 99 },
      { testName: 'Serum Creatinine', value: 0.9, unit: 'mg/dL', referenceRange: '0.6 - 1.0', status: 'normal', confidence: 98 },
      { testName: 'Systolic BP', value: 128, unit: 'mmHg', referenceRange: '90 - 120', status: 'normal', confidence: 97 },
    ],
    doctorRecommendations: ['Good glycemic stability'],
    followUpDate: '2026-05-05',
    aiConfidenceScore: 99,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Early 2026 checkup showing stable glycemic control (HbA1c 6.9%). Prescriptions unchanged.',
    changeHighlights: [],
  },
];

// 5 Distinct Reports for Father (Ramesh Devi)
export const FATHER_REPORTS: MedicalReport[] = [
  {
    id: 'report_f1',
    parentId: 'parent_father',
    uploadDate: '2026-07-10T11:00:00Z',
    visitDate: '2026-07-10',
    doctorName: 'Dr. Evelyn Vance',
    doctorSpecialty: 'Cardiology',
    hospital: 'St. Jude Cardiac Center',
    department: 'Outpatient Cardiology',
    patientName: 'Ramesh Devi',
    reportType: 'prescription',
    fileUrl: makeSampleSvgBase64('Dr. Evelyn Vance', 'Ramesh Devi', 'July 10, 2026', 'Atorvastatin dosage increased from 10mg to 20mg. Amlodipine 5mg added for blood pressure control.'),
    diagnoses: ['Essential Hypertension', 'Hyperlipidemia'],
    medicines: [
      { name: 'Atorvastatin (Lipitor)', dosage: '20 mg', frequency: 'Once daily at bedtime', status: 'changed', previousDosage: '10 mg', confidence: 97 },
      { name: 'Amlodipine (Norvasc)', dosage: '5 mg', frequency: 'Once daily morning', status: 'new', confidence: 96 },
      { name: 'Aspirin (Low Dose)', dosage: '81 mg', frequency: 'Once daily after breakfast', status: 'continued', confidence: 98 },
    ],
    labResults: [
      { testName: 'Systolic BP', value: 148, unit: 'mmHg', referenceRange: '90 - 120', status: 'abnormal_high', confidence: 98 },
      { testName: 'Diastolic BP', value: 92, unit: 'mmHg', referenceRange: '60 - 80', status: 'abnormal_high', confidence: 97 },
      { testName: 'Total Cholesterol', value: 235, unit: 'mg/dL', referenceRange: '< 200', status: 'abnormal_high', confidence: 96 },
      { testName: 'LDL Cholesterol', value: 152, unit: 'mg/dL', referenceRange: '< 100', status: 'abnormal_high', confidence: 95 },
    ],
    doctorRecommendations: ['Low-fat diet', 'Monitor BP every 3 days', 'Lipid panel in 60 days'],
    followUpDate: '2026-09-10',
    aiConfidenceScore: 96,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: "Father's BP elevated at 148/92 mmHg and Total Cholesterol at 235 mg/dL. Dr. Vance increased Atorvastatin to 20mg and added Amlodipine 5mg once daily.",
    changeHighlights: [
      { id: 'fc1', field: 'Atorvastatin', category: 'medicine', oldValue: '10 mg', newValue: '20 mg', description: 'Statin dosage doubled to lower LDL cholesterol.', severity: 'warning' },
      { id: 'fc2', field: 'Amlodipine 5mg', category: 'medicine', newValue: '5 mg daily', description: 'New anti-hypertensive drug added.', severity: 'info' },
    ],
  },
  {
    id: 'report_f2',
    parentId: 'parent_father',
    uploadDate: '2026-05-18T15:30:00Z',
    visitDate: '2026-05-18',
    doctorName: 'Dr. Neil Gupte',
    doctorSpecialty: 'Gastroenterology',
    hospital: 'City Digestive Health Center',
    department: 'Gastroenterology OPD',
    patientName: 'Ramesh Devi',
    reportType: 'prescription',
    fileUrl: makeSampleSvgBase64('Dr. Neil Gupte', 'Ramesh Devi', 'May 18, 2026', 'GERD and Acid Reflux. Prescribed Omeprazole 20mg once daily before breakfast.'),
    diagnoses: ['Gastroesophageal Reflux Disease (GERD)', 'Dyspepsia'],
    medicines: [
      { name: 'Omeprazole (Prilosec)', dosage: '20 mg', frequency: 'Once daily before breakfast', status: 'new', confidence: 95 },
    ],
    labResults: [],
    doctorRecommendations: ['Avoid spicy foods', 'Elevate head of bed'],
    followUpDate: '2026-11-18',
    aiConfidenceScore: 95,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Father visited GI specialist Dr. Neil Gupte for acid reflux. Omeprazole 20mg started for 4 weeks with dietary modifications.',
    changeHighlights: [],
  },
  {
    id: 'report_f3',
    parentId: 'parent_father',
    uploadDate: '2026-03-22T09:15:00Z',
    visitDate: '2026-03-22',
    doctorName: 'Dr. Evelyn Vance',
    doctorSpecialty: 'Cardiology',
    hospital: 'St. Jude Cardiac Center',
    department: 'Cardiology Clinic',
    patientName: 'Ramesh Devi',
    reportType: 'lab',
    fileUrl: makeSampleSvgBase64('Dr. Evelyn Vance', 'Ramesh Devi', 'March 22, 2026', 'Cardiovascular Risk Panel: BP 140/88 mmHg, Total Cholesterol 220 mg/dL.'),
    diagnoses: ['Essential Hypertension', 'Hyperlipidemia'],
    medicines: [
      { name: 'Atorvastatin', dosage: '10 mg', frequency: 'Once daily', status: 'continued', confidence: 98 },
      { name: 'Aspirin', dosage: '81 mg', frequency: 'Once daily', status: 'continued', confidence: 99 },
    ],
    labResults: [
      { testName: 'Systolic BP', value: 140, unit: 'mmHg', referenceRange: '90 - 120', status: 'abnormal_high', confidence: 98 },
      { testName: 'Diastolic BP', value: 88, unit: 'mmHg', referenceRange: '60 - 80', status: 'abnormal_high', confidence: 97 },
      { testName: 'Total Cholesterol', value: 220, unit: 'mg/dL', referenceRange: '< 200', status: 'abnormal_high', confidence: 96 },
      { testName: 'Serum Creatinine', value: 0.9, unit: 'mg/dL', referenceRange: '0.6 - 1.0', status: 'normal', confidence: 99 },
    ],
    doctorRecommendations: ['Maintain current medications', 'Repeat lipid panel in July'],
    followUpDate: '2026-07-10',
    aiConfidenceScore: 97,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Spring 2026 cardiac panel. Blood pressure measured 140/88. Cholesterol slightly elevated at 220 mg/dL. Renal markers normal.',
    changeHighlights: [],
  },
  {
    id: 'report_f4',
    parentId: 'parent_father',
    uploadDate: '2025-11-05T14:00:00Z',
    visitDate: '2025-11-05',
    doctorName: 'Dr. Harold Finch',
    doctorSpecialty: 'Urology',
    hospital: 'Metro Urology Care',
    department: 'Urology OPD',
    patientName: 'Ramesh Devi',
    reportType: 'general',
    fileUrl: makeSampleSvgBase64('Dr. Harold Finch', 'Ramesh Devi', 'Nov 05, 2025', 'Prostate Checkup: PSA 1.8 ng/mL (Normal). No signs of acute BPH.'),
    diagnoses: ['Mild Benign Prostatic Hyperplasia (BPH) Screening'],
    medicines: [
      { name: 'Tamsulosin (Flomax)', dosage: '0.4 mg', frequency: 'Once daily at bedtime', status: 'continued', confidence: 96 },
    ],
    labResults: [
      { testName: 'Serum PSA', value: 1.8, unit: 'ng/mL', referenceRange: '< 4.0', status: 'normal', confidence: 98 },
    ],
    doctorRecommendations: ['Annual PSA screening in Nov 2026'],
    followUpDate: '2026-11-05',
    aiConfidenceScore: 98,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Annual prostate screening by Dr. Finch. PSA level normal at 1.8 ng/mL. Tamsulosin 0.4mg maintained.',
    changeHighlights: [],
  },
  {
    id: 'report_f5',
    parentId: 'parent_father',
    uploadDate: '2025-08-14T10:00:00Z',
    visitDate: '2025-08-14',
    doctorName: 'Dr. Evelyn Vance',
    doctorSpecialty: 'Cardiology',
    hospital: 'St. Jude Cardiac Center',
    department: 'Outpatient Cardiology',
    patientName: 'Ramesh Devi',
    reportType: 'prescription',
    fileUrl: makeSampleSvgBase64('Dr. Evelyn Vance', 'Ramesh Devi', 'Aug 14, 2025', 'Baseline Cardiac Evaluation: Atorvastatin 10mg initiated for hypercholesterolemia.'),
    diagnoses: ['Hyperlipidemia', 'Hypertension Risk'],
    medicines: [
      { name: 'Atorvastatin', dosage: '10 mg', frequency: 'Once daily', status: 'new', confidence: 95 },
      { name: 'Aspirin', dosage: '81 mg', frequency: 'Once daily', status: 'new', confidence: 97 },
    ],
    labResults: [
      { testName: 'Total Cholesterol', value: 242, unit: 'mg/dL', referenceRange: '< 200', status: 'abnormal_high', confidence: 97 },
      { testName: 'Systolic BP', value: 135, unit: 'mmHg', referenceRange: '90 - 120', status: 'abnormal_high', confidence: 96 },
    ],
    doctorRecommendations: ['Initiated statin therapy'],
    followUpDate: '2026-03-22',
    aiConfidenceScore: 96,
    needsReview: false,
    aiMode: 'simulator',
    caregiverSummary: 'Summer 2025 baseline evaluation. Atorvastatin 10mg started for elevated cholesterol (242 mg/dL).',
    changeHighlights: [],
  },
];

export const INITIAL_REPORTS: MedicalReport[] = [...MOTHER_REPORTS, ...FATHER_REPORTS];

export const INITIAL_FOLLOWUPS: FollowUpItem[] = [
  {
    id: 'fm1',
    parentId: 'parent_mother',
    doctorName: 'Dr. Aris Thorne',
    specialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    date: '2026-10-18',
    reason: 'Repeat HbA1c, Fasting Blood Glucose & Kidney Panel',
    status: 'upcoming',
    reportId: 'report_m1',
  },
  {
    id: 'fm2',
    parentId: 'parent_mother',
    doctorName: 'Dr. Vikram Seth',
    specialty: 'Orthopedics',
    hospital: 'City Spine & Joint Care',
    date: '2026-08-15',
    reason: 'Knee Osteoarthritis follow-up',
    status: 'due_soon',
    reportId: 'report_m2',
  },
  {
    id: 'ff1',
    parentId: 'parent_father',
    doctorName: 'Dr. Evelyn Vance',
    specialty: 'Cardiology',
    hospital: 'St. Jude Cardiac Center',
    date: '2026-09-10',
    reason: 'Lipid panel & blood pressure check (Amlodipine response)',
    status: 'upcoming',
    reportId: 'report_f1',
  },
  {
    id: 'ff2',
    parentId: 'parent_father',
    doctorName: 'Dr. Neil Gupte',
    specialty: 'Gastroenterology',
    hospital: 'City Digestive Health Center',
    date: '2026-11-18',
    reason: 'GERD & Omeprazole response evaluation',
    status: 'upcoming',
    reportId: 'report_f2',
  },
];
