import { ParentProfile, MedicalReport, FollowUpItem } from '../types/medical';

export const INITIAL_PARENT_PROFILE: ParentProfile = {
  id: 'parent_lakshmi_1',
  name: 'Lakshmi Devi',
  age: 58,
  gender: 'Female',
  bloodGroup: 'O+',
  relationship: 'Mother',
  primaryCondition: 'Type 2 Diabetes & Hypertension',
  conditions: ['Type 2 Diabetes', 'Hypertension', 'Mild Diabetic Nephropathy Risk'],
  primaryDoctor: 'Dr. Aris Thorne (Endocrinologist)',
  hospital: 'Apex Heart & Metabolic Institute',
  emergencyContactName: 'Rohan Devi (Son / Primary Caregiver)',
  emergencyContactPhone: '+1 (555) 392-8812',
  photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
};

export const INITIAL_REPORTS: MedicalReport[] = [
  {
    id: 'report_2026_07_18',
    uploadDate: '2026-07-18T10:30:00Z',
    visitDate: '2026-07-18',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Outpatient Endocrinology',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    diagnoses: ['Type 2 Diabetes (Uncontrolled)', 'Essential Hypertension'],
    medicines: [
      {
        name: 'Metformin HCl (Glucophage)',
        dosage: '1000 mg',
        frequency: 'Twice daily after meals',
        status: 'changed',
        previousDosage: '500 mg',
        instructions: 'Increased dosage to control post-prandial glucose spikes.',
        confidence: 96,
      },
      {
        name: 'Ramipril (Altace)',
        dosage: '5 mg',
        frequency: 'Once daily at morning',
        status: 'changed',
        previousDosage: '2.5 mg',
        instructions: 'Adjusted dosage for blood pressure optimization and renal protection.',
        confidence: 94,
      },
      {
        name: 'Vitamin D3 (Cholecalciferol)',
        dosage: '60,000 IU',
        frequency: 'Once weekly for 8 weeks',
        status: 'new',
        instructions: 'Prescribed due to deficient serum 25-OH Vitamin D levels.',
        confidence: 92,
      },
    ],
    labResults: [
      {
        testName: 'HbA1c (Glycated Hemoglobin)',
        value: 7.8,
        unit: '%',
        referenceRange: '4.0 - 5.6',
        status: 'abnormal_high',
        confidence: 98,
      },
      {
        testName: 'Fasting Blood Glucose',
        value: 154,
        unit: 'mg/dL',
        referenceRange: '70 - 99',
        status: 'abnormal_high',
        confidence: 96,
      },
      {
        testName: 'Serum Creatinine',
        value: 1.1,
        unit: 'mg/dL',
        referenceRange: '0.6 - 1.0',
        status: 'abnormal_high',
        confidence: 95,
      },
      {
        testName: 'Systolic BP',
        value: 142,
        unit: 'mmHg',
        referenceRange: '90 - 120',
        status: 'abnormal_high',
        confidence: 97,
      },
      {
        testName: 'Diastolic BP',
        value: 88,
        unit: 'mmHg',
        referenceRange: '60 - 80',
        status: 'abnormal_high',
        confidence: 97,
      },
    ],
    doctorRecommendations: [
      'Strict low-sodium and reduced-glycemic diet.',
      'Daily 30-minute brisk walk.',
      'Repeat HbA1c and Kidney Function Test in 90 days.',
      'Monitor home blood pressure twice weekly.',
    ],
    followUpDate: '2026-10-18',
    aiConfidenceScore: 95,
    needsReview: false,
    caregiverSummary:
      "Your mother's diabetes markers (HbA1c increased from 7.4% to 7.8%) and blood pressure remain elevated. Dr. Thorne increased Metformin dosage from 500mg to 1000mg twice daily and Ramipril to 5mg. Vitamin D3 supplementation was started. Kidney markers show mild elevation (Creatinine 1.1 mg/dL). Next follow-up is in 90 days.",
    changeHighlights: [
      {
        id: 'c1',
        field: 'Metformin',
        category: 'medicine',
        oldValue: '500 mg',
        newValue: '1000 mg twice daily',
        description: 'Dosage increased by Dr. Thorne to manage hyperglycemia.',
        severity: 'warning',
      },
      {
        id: 'c2',
        field: 'HbA1c',
        category: 'lab',
        oldValue: '7.4%',
        newValue: '7.8%',
        description: 'Glycemic control worsened over the past 2.5 months.',
        severity: 'warning',
      },
      {
        id: 'c3',
        field: 'Vitamin D3',
        category: 'medicine',
        oldValue: 'None',
        newValue: '60,000 IU weekly',
        description: 'New supplement added for severe deficiency.',
        severity: 'info',
      },
    ],
  },
  {
    id: 'report_2026_06_12',
    uploadDate: '2026-06-12T14:15:00Z',
    visitDate: '2026-06-12',
    doctorName: 'Dr. Vikram Seth',
    doctorSpecialty: 'Orthopedics',
    hospital: 'City Spine & Joint Care',
    department: 'Orthopedic OPD',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    diagnoses: ['Bilateral Knee Osteoarthritis (Grade II)', 'Knee Pain'],
    medicines: [
      {
        name: 'Naproxen Sodium (Aleve)',
        dosage: '500 mg',
        frequency: 'Twice daily after meals for 10 days',
        status: 'new',
        instructions: 'Take with food for joint inflammation.',
        confidence: 74,
      },
      {
        name: 'Glucosamine Sulfate',
        dosage: '1500 mg',
        frequency: 'Once daily',
        status: 'new',
        instructions: 'Joint cartilage supplement.',
        confidence: 78,
      },
    ],
    labResults: [],
    doctorRecommendations: [
      'Avoid climbing stairs.',
      'Apply ice pack to knees twice daily.',
      'Physiotherapy quadriceps strengthening exercises.',
    ],
    followUpDate: '2026-08-15',
    aiConfidenceScore: 74,
    needsReview: true, // Needs manual review demo!
    caregiverSummary:
      'Report from Dr. Vikram Seth (Orthopedics) for knee joint pain. High-dose Naproxen (NSAID) was prescribed for 10 days along with Glucosamine. [AI Flag]: Naproxen presents a potential conflict with her renal parameters (Creatinine 1.1). Manual review recommended.',
    changeHighlights: [
      {
        id: 'c4',
        field: 'Naproxen 500mg',
        category: 'medicine',
        newValue: '500 mg twice daily',
        description: 'New NSAID painkiller prescribed. Potential renal warning.',
        severity: 'critical',
      },
    ],
    doctorConflicts: [
      {
        id: 'conflict_1',
        severity: 'critical',
        title: 'NSAID & Kidney Risk Conflict',
        description:
          'Dr. Vikram Seth (Orthopedics) prescribed Naproxen 500mg (NSAID painkiller). However, Dr. Aris Thorne (Endocrinologist) flagged elevated Creatinine (1.1 mg/dL) indicating mild renal stress. NSAIDs can further impair kidney filtration.',
        doctorNames: ['Dr. Vikram Seth (Orthopedics)', 'Dr. Aris Thorne (Endocrinology)'],
        reportIds: ['report_2026_06_12', 'report_2026_07_18'],
        recommendation:
          'Consult Dr. Thorne before starting Naproxen, or request an alternative kidney-safe analgesic (like Acetaminophen). CareLens does not alter prescriptions.',
      },
    ],
  },
  {
    id: 'report_2026_05_05',
    uploadDate: '2026-05-05T09:00:00Z',
    visitDate: '2026-05-05',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Metabolic Lab',
    patientName: 'Lakshmi Devi',
    reportType: 'lab',
    diagnoses: ['Type 2 Diabetes', 'Hypertension'],
    medicines: [
      {
        name: 'Metformin HCl',
        dosage: '500 mg',
        frequency: 'Twice daily',
        status: 'continued',
        confidence: 97,
      },
      {
        name: 'Ramipril',
        dosage: '2.5 mg',
        frequency: 'Once daily',
        status: 'continued',
        confidence: 96,
      },
    ],
    labResults: [
      {
        testName: 'HbA1c (Glycated Hemoglobin)',
        value: 7.4,
        unit: '%',
        referenceRange: '4.0 - 5.6',
        status: 'abnormal_high',
        confidence: 99,
      },
      {
        testName: 'Fasting Blood Glucose',
        value: 140,
        unit: 'mg/dL',
        referenceRange: '70 - 99',
        status: 'abnormal_high',
        confidence: 98,
      },
      {
        testName: 'Serum Creatinine',
        value: 1.0,
        unit: 'mg/dL',
        referenceRange: '0.6 - 1.0',
        status: 'normal',
        confidence: 97,
      },
      {
        testName: 'Total Cholesterol',
        value: 210,
        unit: 'mg/dL',
        referenceRange: '< 200',
        status: 'abnormal_high',
        confidence: 95,
      },
      {
        testName: 'Systolic BP',
        value: 136,
        unit: 'mmHg',
        referenceRange: '90 - 120',
        status: 'abnormal_high',
        confidence: 96,
      },
    ],
    doctorRecommendations: [
      'Maintain dietary restrictions.',
      'Repeat lipid profile in 6 months.',
    ],
    followUpDate: '2026-07-15',
    aiConfidenceScore: 97,
    needsReview: false,
    caregiverSummary:
      'Routine 3-month diabetes follow-up panel. HbA1c recorded at 7.4% (up from 6.9% in January). Blood pressure was 136/84. Metformin 500mg maintained.',
    changeHighlights: [
      {
        id: 'c5',
        field: 'HbA1c',
        category: 'lab',
        oldValue: '6.9%',
        newValue: '7.4%',
        description: 'HbA1c increased by 0.5% over 3.5 months.',
        severity: 'warning',
      },
    ],
  },
  {
    id: 'report_2026_01_20',
    uploadDate: '2026-01-20T11:20:00Z',
    visitDate: '2026-01-20',
    doctorName: 'Dr. Maya Lin',
    doctorSpecialty: 'Ophthalmology',
    hospital: 'Vision First Eye Hospital',
    department: 'Retinal Clinic',
    patientName: 'Lakshmi Devi',
    reportType: 'general',
    diagnoses: ['Diabetic Retinopathy Screening', 'Presbyopia'],
    medicines: [
      {
        name: 'Lubricating Eye Drops (Carboxymethylcellulose)',
        dosage: '1 drop',
        frequency: '4 times daily both eyes',
        status: 'new',
        confidence: 98,
      },
    ],
    labResults: [],
    doctorRecommendations: [
      'Fundus examination normal. No active diabetic macular edema or diabetic retinopathy.',
      'Updated reading glasses prescription (+2.25D).',
      'Annual retinal scan screening required in January 2027.',
    ],
    followUpDate: '2027-01-20',
    aiConfidenceScore: 98,
    needsReview: false,
    caregiverSummary:
      'Annual diabetic eye screening by Dr. Maya Lin. Retinal scan shows NO signs of diabetic retinopathy. Reading glasses updated. Lubricating eye drops prescribed for dry eye symptoms.',
    changeHighlights: [
      {
        id: 'c6',
        field: 'Retinal Examination',
        category: 'recommendation',
        newValue: 'Clear / Normal',
        description: 'No diabetic macular edema detected.',
        severity: 'info',
      },
    ],
  },
  {
    id: 'report_2026_01_10',
    uploadDate: '2026-01-10T16:00:00Z',
    visitDate: '2026-01-10',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Endocrinology Clinic',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    diagnoses: ['Type 2 Diabetes', 'Mild Essential Hypertension'],
    medicines: [
      {
        name: 'Metformin HCl',
        dosage: '500 mg',
        frequency: 'Twice daily',
        status: 'continued',
        confidence: 99,
      },
      {
        name: 'Ramipril',
        dosage: '2.5 mg',
        frequency: 'Once daily',
        status: 'continued',
        confidence: 99,
      },
    ],
    labResults: [
      {
        testName: 'HbA1c (Glycated Hemoglobin)',
        value: 6.9,
        unit: '%',
        referenceRange: '4.0 - 5.6',
        status: 'abnormal_high',
        confidence: 99,
      },
      {
        testName: 'Serum Creatinine',
        value: 0.9,
        unit: 'mg/dL',
        referenceRange: '0.6 - 1.0',
        status: 'normal',
        confidence: 98,
      },
      {
        testName: 'Systolic BP',
        value: 128,
        unit: 'mmHg',
        referenceRange: '90 - 120',
        status: 'normal',
        confidence: 97,
      },
    ],
    doctorRecommendations: [
      'Good glycemic control achieved.',
      'Continue current regimen.',
    ],
    followUpDate: '2026-05-05',
    aiConfidenceScore: 99,
    needsReview: false,
    caregiverSummary:
      'Early 2026 checkup showing stable glycemic control (HbA1c 6.9%). Blood pressure was well-controlled at 128/82. Prescriptions unchanged.',
    changeHighlights: [],
  },
  {
    id: 'report_2025_09_14',
    uploadDate: '2025-09-14T10:00:00Z',
    visitDate: '2025-09-14',
    doctorName: 'Dr. Aris Thorne',
    doctorSpecialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    department: 'Outpatient Clinic',
    patientName: 'Lakshmi Devi',
    reportType: 'prescription',
    diagnoses: ['Type 2 Diabetes Mellitus'],
    medicines: [
      {
        name: 'Metformin HCl',
        dosage: '500 mg',
        frequency: 'Twice daily',
        status: 'continued',
        confidence: 96,
      },
      {
        name: 'Ramipril',
        dosage: '2.5 mg',
        frequency: 'Once daily',
        status: 'new',
        instructions: 'Initiated for mild baseline hypertension.',
        confidence: 95,
      },
    ],
    labResults: [
      {
        testName: 'HbA1c (Glycated Hemoglobin)',
        value: 6.5,
        unit: '%',
        referenceRange: '4.0 - 5.6',
        status: 'abnormal_high',
        confidence: 97,
      },
      {
        testName: 'Systolic BP',
        value: 138,
        unit: 'mmHg',
        referenceRange: '90 - 120',
        status: 'abnormal_high',
        confidence: 96,
      },
    ],
    doctorRecommendations: [
      'Ramipril 2.5mg added to manage blood pressure.',
    ],
    followUpDate: '2026-01-10',
    aiConfidenceScore: 96,
    needsReview: false,
    caregiverSummary:
      'Fall 2025 consultation. Ramipril 2.5mg was initiated for mild hypertension. HbA1c was at baseline target of 6.5%.',
    changeHighlights: [
      {
        id: 'c7',
        field: 'Ramipril 2.5mg',
        category: 'medicine',
        newValue: '2.5 mg once daily',
        description: 'New anti-hypertensive medication started.',
        severity: 'info',
      },
    ],
  },
];

export const INITIAL_FOLLOWUPS: FollowUpItem[] = [
  {
    id: 'f1',
    doctorName: 'Dr. Aris Thorne',
    specialty: 'Endocrinology',
    hospital: 'Apex Heart & Metabolic Institute',
    date: '2026-10-18',
    reason: 'Repeat HbA1c, Fasting Blood Glucose, & Kidney Function Panel',
    status: 'upcoming',
    reportId: 'report_2026_07_18',
  },
  {
    id: 'f2',
    doctorName: 'Dr. Vikram Seth',
    specialty: 'Orthopedics',
    hospital: 'City Spine & Joint Care',
    date: '2026-08-15',
    reason: 'Knee Osteoarthritis follow-up & pain response evaluation',
    status: 'due_soon',
    reportId: 'report_2026_06_12',
  },
  {
    id: 'f3',
    doctorName: 'Dr. Maya Lin',
    specialty: 'Ophthalmology',
    hospital: 'Vision First Eye Hospital',
    date: '2027-01-20',
    reason: 'Annual Diabetic Retinopathy Fundus Examination',
    status: 'upcoming',
    reportId: 'report_2026_01_20',
  },
];
